koma.kcui:
    clusters:

micronaut:
    application:
        name: kcui
    http.client:
        read-timeout: 1m
    server:
        cors:
            enabled: true
    router:
        static-resources:
            default:
                paths: classpath:public
                mapping: /**
                enabled: true

netty:
    default:
        allocator:
            max-order: 3